name = "memos-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2026-05-20"

[build]
command = "sh scripts/build-worker.sh"

[assets]
directory = "./dist/static"
binding = "ASSETS"
html_handling = "auto-trailing-slash"

[[d1_databases]]
binding = "DB"
database_name = "memos-db"
database_id = "59e01dfb-26a0-43db-8eed-4eca5f88fd33"

[[r2_buckets]]
binding = "MEMOS_BUCKET"
bucket_name = "memos-storage"

[vars]
ENVIRONMENT = "production"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SSEHub"]

[[migrations]]
tag = "v2"
deleted_classes = ["SSEHub"]

[triggers]
crons = ["0 18 * * *"]
